### ISSUE TITLE
Cipher Doesn't Deal with Uppercase Letters

### ISSUE THREAD

**Issue by AverageHomosapien** [siwells/set08101#3]
Just want to let you know that the ROT13 encoder doesn't support uppercase letters. The rest it will change fine.

**Comment by siwells** [comment]
I know. The example is meant to be indicative of how to go about addressing the problem by processing each letter. I wanted it to be fairly minimal so that the learning opportunity wasn't obscured by more complicated code. It's one of the drawbacks of providing examples they are either complete (but complex & difficult to understand) or else simple (& miss out cases). On this occasion I leaned towards simple. Plus, if I'd included all of the checking and upper/lower/symbol/number handling then there'd be nothing left for you folk to work on  ;)
